assets:
  - elevforeningen.sql.gz
steps:
  - name: ProboCI site setup
    plugin: Drupal
    makeFile: build-elevforeningen.make
    database: elevforeningen.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    revertFeatures: true
  - name: Make directory for site
    command: 'mkdir /var/www/html/sites/elevforeningen.local; mkdir /var/www/html/sites/elevforeningen.local/files; mkdir /var/www/html/sites/elevforeningen.local/private; mkdir /var/www/html/sites/elevforeningen.local/private/temp'
  - name: Fix permissions
    command: 'chown -R www-data:www-data /var/www/html/sites/elevforeningen.local; chmod 777 -R /var/www/html/sites/elevforeningen.local'
  - name: Generate login link
    command: 'drush --root="/var/www/html" uli'
  - name: Enable stage_file_proxy
    command: 'drush --root="/var/www/html" en stage_file_proxy -y; drush variable-set stage_file_proxy_origin "http://elevforeningen.vih.dk"'
  - name: Reroute e-mails
    command: 'drush --root="/var/www/html" en reroute_email -y; drush variable-set reroute_email_enable 1; drush variable-set reroute_email_address "webmaster@vih.dk"'
  - name: Disable certain modules
    command: 'drush --root="/var/www/html" pm-disable googleanalytics'
