language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8
  
install:
  - sudo apt-get update > /dev/null
  - "mysql -e 'create database drupal;'"

  # Install the latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*@dev
  - phpenv rehash

  # Build Behat dependencies
  - cd ./tests/behat
  - composer install --no-interaction
  - cd ../../../

  # Build Codebase
  - mkdir private_files
  - mkdir profiles
  - mv elevforeningen-build profiles/vih_dk
  - mkdir drupal
  - mv profiles drupal/

  # Test the current branch
  - cd drupal
  - drush make --prepare-install profiles/vih_dk/build-elevforening.make --yes
  - cd ../

  # Setup files
  - sudo chmod -R 777 drupal/sites/all

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:

  - cd drupal
  - drush si commons --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="VIH Elevforening" --yes
  - drush en ef_deploy -y
  - drush mi --all
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - until netstat -an 2>/dev/null | grep '8888.*LISTEN'; do true; done
  - cd profiles/vih_dk/tests/behat

  # Make the Travis tests repos agnostic by injecting drupal_root with BEHAT_PARAMS
  - BUILD_OWNER=`dirname $TRAVIS_BUILD_DIR`
  - export BEHAT_PARAMS="extensions[Drupal\\DrupalExtension\\Extension][drupal][drupal_root]=$BUILD_OWNER/drupal"

script:

  - ./bin/behat --config behat.travis.yml
