language: php

php:
  - 5.3

mysql:
  database: drupal
  username: root
  encoding: utf8
  
before_script:
  - "mysql -e 'create database drupal;'"
  - pear channel-discover pear.drush.org
  - pear install drush/drush
  - phpenv rehash
  - drush make vih_elevforening.build ../elevforeningen.vih.dk
  - cd ../elevforeningen.vih.dk
  - sudo chmod -R 777 sites/all/modules
  - drush si vih_elevforening --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=VIH@2012 --site-mail=admin@example.com --site-name="elevforeningen.vih.dk" --yes
  - drush cc all --yes

script: 
  - test -d profiles/vih_elevforening
  - test -d profiles/vih_elevforening/modules/contrib
  - test -d profiles/vih_elevforening/modules/elevforening
  - test -d profiles/vih_elevforening/themes
