language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8
  
install:
  - sudo apt-get update > /dev/null
  - "mysql -e 'create database drupal;'"

  # Install the latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require drush/drush:6.*
  - phpenv rehash

  # Be in correct directory
  - cd ../

  # Build Codebase
  - mkdir private_files
  - mkdir profiles
  - mv elevforeningen-build profiles/vih_dk
  - mkdir drupal
  - mv profiles drupal/

  # Test the current branch
  - cd drupal
  - drush make --prepare-install profiles/vih_dk/build-elevforening.make --yes
  - cd ../

  # Setup files
  - sudo chmod -R 777 drupal/sites/all

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:

  - cd drupal
  - drush si vih_elevforening --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="VIH Elevforening" --yes
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - until netstat -an 2>/dev/null | grep '8888.*LISTEN'; do true; done

script: 
  - test -d profiles/vih_elevforening
  - test -d sites/all/modules/contrib
  - test -d sites/all/modules/elevforening
