language: php
sudo: false

php:

  - 5.5

matrix:
  include:
    - php: 5.6
  allow_failures:
    - php: 5.6
  fast_finish: true

mysql:
  database: drupal
  username: root
  encoding: utf8

# Cache Composer & Drush directories.
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache

install:

  - "mysql -e 'create database drupal;'"

  # Install latest Drush 6.
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "drush/drush:6.*"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Build Behat dependencies
  - cd ./tests/behat
  - composer install --no-interaction
  - cd ../../../

   # Setting Behat environment
  - DISTRO=`echo $TRAVIS_BUILD_DIR | sed -e "s/\/[^\/]*$//"`
  - export BEHAT_PARAMS="{\"extensions\":{\"Drupal\\\DrupalExtension\":{\"drupal\":{\"drupal_root\":\"$DISTRO/drupal\"}}}}"

  # Build Codebase
  - mkdir private_files
  - mkdir profiles
  - mv elevforeningen-build profiles/vih_dk
  - mkdir drupal
  - mv profiles drupal/

  # Test the current branch
  - cd drupal
  - drush make --prepare-install profiles/vih_dk/build-elevforening.make --yes
  - cd ../

  # Setup files
  - sudo chmod -R 777 drupal/sites/all

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Enable APC
  - echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.shm_size=256M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL connection timeout on the PHP end.
  - echo "mysql.connect_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "default_socket_timeout=3000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Increase the MySQL server timetout and packet size.
  - mysql -e "SET GLOBAL wait_timeout = 36000;"
  - mysql -e "SET GLOBAL max_allowed_packet = 33554432;"

before_script:

  - cd drupal
  - drush si commons --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="VIH Elevforening" --yes
  - drush en ef_deploy -y
  - drush mi --all

  # Start builtin server.
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - until netstat -an 2>/dev/null | grep '8888.*LISTEN'; do true; done
  - cd profiles/vih_dk/tests/behat

script:

  # Check for overridden features
  - ../../scripts/check-overridden.sh

  # Run Behat tests
  - ./bin/behat --config behat.travis.yml
